services:
  ai-demo-dev-db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - ./src/main/resources/db/init/:/docker-entrypoint-initdb.d/
